import { PowerOption } from '../../../interfaces';

export class PoderesAlternativosList {
    items: PowerOption[] = [
        {"id":1,"nome":"Absor\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":2,"nome":"Adapta\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":3,"nome":"Alongamento","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":4,"nome":"Animar Objetos","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":5,"nome":"Armadilha","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":6,"nome":"Atordoar","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":7,"nome":"Bols\u00e3o Dimensional","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":8,"nome":"Campo de For\u00e7a","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":9,"nome":"Camuflagem","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":10,"nome":"Compreender","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":11,"nome":"Comunica\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":12,"nome":"Confus\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":13,"nome":"Controle Ambiental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":14,"nome":"Controle Cin\u00e9tico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":15,"nome":"Controle Clim\u00e1tico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":16,"nome":"Controle de (Elemento)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":17,"nome":"Controle de Animais","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":18,"nome":"Controle de Energia C\u00f3smica","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":19,"nome":"Controle de Escurid\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":20,"nome":"Controle de Fogo Infernal","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":21,"nome":"Controle de Fric\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":22,"nome":"Controle de Frio","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":23,"nome":"Controle de Luz","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":24,"nome":"Controle de Plantas","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":25,"nome":"Controle de Plasma","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":26,"nome":"Controle de Poder","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":27,"nome":"Controle de Radia\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":28,"nome":"Controle de Sorte","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":29,"nome":"Controle de Vibra\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":30,"nome":"Controle El\u00e9trico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":31,"nome":"Controle Emocional","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":32,"nome":"Controle Espacial","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":33,"nome":"Controle Gravitacional","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":34,"nome":"Controle Magn\u00e9tico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":35,"nome":"Controle Mental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":36,"nome":"Controle S\u00f4nico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":37,"nome":"Controle Temporal","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":38,"nome":"Controle Vital","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":39,"nome":"Corros\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":40,"nome":"Crescimento","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":41,"nome":"Criar Objeto","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":42,"nome":"Cura","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":43,"nome":"Deflex\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":44,"nome":"Densidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":45,"nome":"Derrubar","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":46,"nome":"Desintegra\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":47,"nome":"Dispositivo","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":48,"nome":"Drenar (Caracter\u00edstica)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":49,"nome":"Duplica\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":50,"nome":"Elo Eletr\u00f4nico","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":51,"nome":"Encolhimento","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":52,"nome":"Escava\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":53,"nome":"Escudo","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":54,"nome":"Escudo Mental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":55,"nome":"Escudo Sensorial","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":56,"nome":"Fadiga","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":57,"nome":"Forma (Alternativa)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":58,"nome":"Forma Astral","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":59,"nome":"Fortalecer (Caracter\u00edstica)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":60,"nome":"Fus\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":61,"nome":"Giro","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":62,"nome":"Golpe","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":63,"nome":"Habilidade Aumentada","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":64,"nome":"Ilus\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":65,"nome":"Imita\u00e7\u00e3o de (Caracter\u00edstica)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":66,"nome":"Imita\u00e7\u00e3o de Animais","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":67,"nome":"Imita\u00e7\u00e3o de Objetos","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":68,"nome":"Im\u00f3vel","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":69,"nome":"Imunidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":70,"nome":"Intangibilidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":71,"nome":"Invisibilidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":72,"nome":"Invocar (Capanga)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":73,"nome":"Leitura Mental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":74,"nome":"Magia","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":75,"nome":"Membros Adicionais","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":76,"nome":"Metamorfose","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":77,"nome":"Morfar","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":78,"nome":"Nata\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":79,"nome":"Nausear","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":80,"nome":"N\u00eamesis","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":81,"nome":"Nulificar (Poder)","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":82,"nome":"Obscurecer","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":83,"nome":"Paralisia","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":84,"nome":"Pasmar","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":85,"nome":"PES","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":86,"nome":"Possess\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":87,"nome":"Prote\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":88,"nome":"Raio","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":89,"nome":"Rajada Mental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":90,"nome":"Rapidez","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":91,"nome":"Regenera\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":92,"nome":"Salto","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":93,"nome":"Separa\u00e7\u00e3o Anat\u00f4mica","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":94,"nome":"Sufocar","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":95,"nome":"Superfor\u00e7a","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":96,"nome":"Supermovimento","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":97,"nome":"Supersentidos","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":98,"nome":"Supervelocidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":99,"nome":"Telecinesia","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":100,"nome":"Telepatia","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":101,"nome":"Teleporte","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":102,"nome":"Transfer\u00eancia","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":103,"nome":"Transforma\u00e7\u00e3o","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":104,"nome":"Troca Mental","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":105,"nome":"Velocidade","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":106,"nome":"Viagem Espacial","modificador":1,"modificadores":[1,2],"checked":false},
        {"id":107,"nome":"Voo","modificador":1,"modificadores":[1,2],"checked":false},
    ];
}