import { Power } from './../../../interfaces';

export class PowersList {
    items: Power[] = [
        {"poder_id":1,"nome":"Absor\u00e7\u00e3o","custo":4,"custos":[4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":2,"nome":"Adapta\u00e7\u00e3o","custo":6,"custos":[6],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":3,"nome":"Alongamento","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":4,"nome":"Animar Objetos","custo":3,"custos":[3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":5,"nome":"Armadilha","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":6,"nome":"Atordoar","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":7,"nome":"Bols\u00e3o Dimensional","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":8,"nome":"Campo de For\u00e7a","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":9,"nome":"Camuflagem","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":10,"nome":"Compreender","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":11,"nome":"Comunica\u00e7\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":12,"nome":"Confus\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":13,"nome":"Controle Ambiental","custo":1,"custos":[1,2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":14,"nome":"Controle Cin\u00e9tico","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":15,"nome":"Controle Clim\u00e1tico","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":16,"nome":"Controle de (Elemento)","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":17,"nome":"Controle de Animais","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":18,"nome":"Controle de Energia C\u00f3smica","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":19,"nome":"Controle de Escurid\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":20,"nome":"Controle de Fogo Infernal","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":21,"nome":"Controle de Fric\u00e7\u00e3o","custo":3,"custos":[3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":22,"nome":"Controle de Frio","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":23,"nome":"Controle de Luz","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":24,"nome":"Controle de Plantas","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":25,"nome":"Controle de Plasma","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":26,"nome":"Controle de Poder","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":27,"nome":"Controle de Radia\u00e7\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":28,"nome":"Controle de Sorte","custo":3,"custos":[3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":29,"nome":"Controle de Vibra\u00e7\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":30,"nome":"Controle El\u00e9trico","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":31,"nome":"Controle Emocional","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":32,"nome":"Controle Espacial","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":33,"nome":"Controle Gravitacional","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":34,"nome":"Controle Magn\u00e9tico","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":35,"nome":"Controle Mental","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":36,"nome":"Controle S\u00f4nico","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":37,"nome":"Controle Temporal","custo":7,"custos":[7],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":38,"nome":"Controle Vital","custo":4,"custos":[4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":39,"nome":"Corros\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":40,"nome":"Crescimento","custo":3,"custos":[3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":41,"nome":"Criar Objeto","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":42,"nome":"Cura","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":43,"nome":"Deflex\u00e3o","custo":1,"custos":[1,2,3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":44,"nome":"Densidade","custo":3,"custos":[3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":45,"nome":"Derrubar","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":46,"nome":"Desintegra\u00e7\u00e3o","custo":4,"custos":[4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":47,"nome":"Dispositivo","custo":3,"custos":[3,4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":48,"nome":"Drenar (Caracter\u00edstica)","custo":1,"custos":[1,2,3,4,5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":49,"nome":"Duplica\u00e7\u00e3o","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":50,"nome":"Elo Eletr\u00f4nico","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":51,"nome":"Encolhimento","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":52,"nome":"Escava\u00e7\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":53,"nome":"Escudo","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":54,"nome":"Escudo Mental","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":55,"nome":"Escudo Sensorial","custo":1,"custos":[1,2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":56,"nome":"Fadiga","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":57,"nome":"Forma (Alternativa)","custo":5,"custos":[5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":58,"nome":"Forma Astral","custo":5,"custos":[5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":59,"nome":"Fortalecer (Caracter\u00edstica)","custo":1,"custos":[1,2,3,4,5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":60,"nome":"Fus\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":61,"nome":"Giro","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":62,"nome":"Golpe","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":63,"nome":"Habilidade Aumentada","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":64,"nome":"Ilus\u00e3o","custo":1,"custos":[1,2,3,4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":65,"nome":"Imita\u00e7\u00e3o de (Caracter\u00edstica)","custo":1,"custos":[1,2,3,4,5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":66,"nome":"Imita\u00e7\u00e3o de Animais","custo":9,"custos":[9],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":67,"nome":"Imita\u00e7\u00e3o de Objetos","custo":6,"custos":[6],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":68,"nome":"Im\u00f3vel","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":69,"nome":"Imunidade","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":70,"nome":"Intangibilidade","custo":5,"custos":[5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":71,"nome":"Invisibilidade","custo":4,"custos":[4,5,6,7,8],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":72,"nome":"Invocar (Capanga)","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":73,"nome":"Leitura Mental","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":74,"nome":"Magia","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":75,"nome":"Membros Adicionais","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":76,"nome":"Metamorfose","custo":8,"custos":[8],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":77,"nome":"Morfar","custo":1,"custos":[1,2,3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":78,"nome":"Nata\u00e7\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":79,"nome":"Nausear","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":80,"nome":"N\u00eamesis","custo":8,"custos":[8],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":81,"nome":"Nulificar (Poder)","custo":1,"custos":[1,2,3],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":82,"nome":"Obscurecer","custo":1,"custos":[1,2,3,4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":83,"nome":"Paralisia","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":84,"nome":"Pasmar","custo":1,"custos":[1,2,3,4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":85,"nome":"PES","custo":1,"custos":[1,2,3,4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":86,"nome":"Possess\u00e3o","custo":4,"custos":[4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":87,"nome":"Prote\u00e7\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":88,"nome":"Raio","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":89,"nome":"Rajada Mental","custo":4,"custos":[4],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":90,"nome":"Rapidez","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":91,"nome":"Regenera\u00e7\u00e3o","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":92,"nome":"Salto","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":93,"nome":"Separa\u00e7\u00e3o Anat\u00f4mica","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":94,"nome":"Sufocar","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":95,"nome":"Superfor\u00e7a","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":96,"nome":"Supermovimento","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":97,"nome":"Supersentidos","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":98,"nome":"Supervelocidade","custo":5,"custos":[5],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":99,"nome":"Telecinesia","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":100,"nome":"Telepatia","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":101,"nome":"Teleporte","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":102,"nome":"Transfer\u00eancia","custo":2,"custos":[2,3,4,5,6,7,8,9,10],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":103,"nome":"Transforma\u00e7\u00e3o","custo":3,"custos":[3,4,5,6],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":104,"nome":"Troca Mental","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":105,"nome":"Velocidade","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":106,"nome":"Viagem Espacial","custo":1,"custos":[1],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
        {"poder_id":107,"nome":"Voo","custo":2,"custos":[2],"graduacao":1,"checked":false,"extras":[],"falhas":[],"opcoes":[],"poderes_alternativos":[]},
    ]
}